name: Builder

env:
  BUILD_ARGS: "--test"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - aarch64

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Determine build mode
        run: |
          if [[ -z "${{ github.head_ref }}" ]] && [[ "${{ github.event_name }}" == "push" ]]; then
            echo "BUILD_ARGS=" >> $GITHUB_ENV;
          fi

      - name: Login to GitHub Container Registry
        if: env.BUILD_ARGS != '--test'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build add-on
        uses: home-assistant/builder@2026.02.1
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            --${{ matrix.arch }} \
            --target /data/alarmdotcom_cameras \
            --image "alarmdotcom-cameras-{arch}" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon
