name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Build & publish ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - aarch64

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }}
            --target alarmdotcom_cameras
            --docker-hub ghcr.io/${{ github.repository_owner }}
